[toolchain]
anchor_version = "0.32.1"
package_manager = "npm"

[features]
resolution = true
skip-lint = false

[programs.devnet]
cora_battle = "Azn65FT27X2VpXHgLCXPCqjgWKEeveVzGqEvZcNp2Lic"

[programs.localnet]
cora_battle = "Azn65FT27X2VpXHgLCXPCqjgWKEeveVzGqEvZcNp2Lic"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test:local"
